package com.redobj.control.analysis.dao;

import com.redobj.control.analysis.bean.Environment;
import com.redobj.control.analysis.bean.EnvironmentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EnvironmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table environment
     *
     * @mbg.generated Sat Jan 13 14:37:33 CST 2018
     */
    long countByExample(EnvironmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table environment
     *
     * @mbg.generated Sat Jan 13 14:37:33 CST 2018
     */
    int deleteByExample(EnvironmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table environment
     *
     * @mbg.generated Sat Jan 13 14:37:33 CST 2018
     */
    int deleteByPrimaryKey(Integer environmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table environment
     *
     * @mbg.generated Sat Jan 13 14:37:33 CST 2018
     */
    int insert(Environment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table environment
     *
     * @mbg.generated Sat Jan 13 14:37:33 CST 2018
     */
    int insertSelective(Environment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table environment
     *
     * @mbg.generated Sat Jan 13 14:37:33 CST 2018
     */
    List<Environment> selectByExample(EnvironmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table environment
     *
     * @mbg.generated Sat Jan 13 14:37:33 CST 2018
     */
    Environment selectByPrimaryKey(Integer environmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table environment
     *
     * @mbg.generated Sat Jan 13 14:37:33 CST 2018
     */
    int updateByExampleSelective(@Param("record") Environment record, @Param("example") EnvironmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table environment
     *
     * @mbg.generated Sat Jan 13 14:37:33 CST 2018
     */
    int updateByExample(@Param("record") Environment record, @Param("example") EnvironmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table environment
     *
     * @mbg.generated Sat Jan 13 14:37:33 CST 2018
     */
    int updateByPrimaryKeySelective(Environment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table environment
     *
     * @mbg.generated Sat Jan 13 14:37:33 CST 2018
     */
    int updateByPrimaryKey(Environment record);
}