package com.redobj.control.analysis.core.dao;

import com.redobj.control.analysis.core.bean.WaitSpider;
import com.redobj.control.analysis.core.bean.WaitSpiderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WaitSpiderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wait_spider
     *
     * @mbg.generated Sun Jan 14 01:30:18 CST 2018
     */
    long countByExample(WaitSpiderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wait_spider
     *
     * @mbg.generated Sun Jan 14 01:30:18 CST 2018
     */
    int deleteByExample(WaitSpiderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wait_spider
     *
     * @mbg.generated Sun Jan 14 01:30:18 CST 2018
     */
    int deleteByPrimaryKey(Integer waitId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wait_spider
     *
     * @mbg.generated Sun Jan 14 01:30:18 CST 2018
     */
    int insert(WaitSpider record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wait_spider
     *
     * @mbg.generated Sun Jan 14 01:30:18 CST 2018
     */
    int insertSelective(WaitSpider record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wait_spider
     *
     * @mbg.generated Sun Jan 14 01:30:18 CST 2018
     */
    List<WaitSpider> selectByExample(WaitSpiderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wait_spider
     *
     * @mbg.generated Sun Jan 14 01:30:18 CST 2018
     */
    WaitSpider selectByPrimaryKey(Integer waitId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wait_spider
     *
     * @mbg.generated Sun Jan 14 01:30:18 CST 2018
     */
    int updateByExampleSelective(@Param("record") WaitSpider record, @Param("example") WaitSpiderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wait_spider
     *
     * @mbg.generated Sun Jan 14 01:30:18 CST 2018
     */
    int updateByExample(@Param("record") WaitSpider record, @Param("example") WaitSpiderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wait_spider
     *
     * @mbg.generated Sun Jan 14 01:30:18 CST 2018
     */
    int updateByPrimaryKeySelective(WaitSpider record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wait_spider
     *
     * @mbg.generated Sun Jan 14 01:30:18 CST 2018
     */
    int updateByPrimaryKey(WaitSpider record);
}