package com.redobj.repository.web.bean;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_id
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_name
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_pwd
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    private String userPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_power
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    private String userPower;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_lastlogin
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    private Date userLastlogin;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_id
     *
     * @return the value of user.user_id
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_id
     *
     * @param userId the value for user.user_id
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_name
     *
     * @return the value of user.user_name
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_name
     *
     * @param userName the value for user.user_name
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_pwd
     *
     * @return the value of user.user_pwd
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    public String getUserPwd() {
        return userPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_pwd
     *
     * @param userPwd the value for user.user_pwd
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    public void setUserPwd(String userPwd) {
        this.userPwd = userPwd == null ? null : userPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_power
     *
     * @return the value of user.user_power
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    public String getUserPower() {
        return userPower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_power
     *
     * @param userPower the value for user.user_power
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    public void setUserPower(String userPower) {
        this.userPower = userPower == null ? null : userPower.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_lastlogin
     *
     * @return the value of user.user_lastlogin
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    public Date getUserLastlogin() {
        return userLastlogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_lastlogin
     *
     * @param userLastlogin the value for user.user_lastlogin
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    public void setUserLastlogin(Date userLastlogin) {
        this.userLastlogin = userLastlogin;
    }
}