package com.redobj.repository.core.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class EnvironmentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table environment
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table environment
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table environment
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table environment
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    public EnvironmentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table environment
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table environment
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table environment
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table environment
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table environment
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table environment
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table environment
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table environment
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table environment
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table environment
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table environment
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andEnvironmentIdIsNull() {
            addCriterion("environment_id is null");
            return (Criteria) this;
        }

        public Criteria andEnvironmentIdIsNotNull() {
            addCriterion("environment_id is not null");
            return (Criteria) this;
        }

        public Criteria andEnvironmentIdEqualTo(Integer value) {
            addCriterion("environment_id =", value, "environmentId");
            return (Criteria) this;
        }

        public Criteria andEnvironmentIdNotEqualTo(Integer value) {
            addCriterion("environment_id <>", value, "environmentId");
            return (Criteria) this;
        }

        public Criteria andEnvironmentIdGreaterThan(Integer value) {
            addCriterion("environment_id >", value, "environmentId");
            return (Criteria) this;
        }

        public Criteria andEnvironmentIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("environment_id >=", value, "environmentId");
            return (Criteria) this;
        }

        public Criteria andEnvironmentIdLessThan(Integer value) {
            addCriterion("environment_id <", value, "environmentId");
            return (Criteria) this;
        }

        public Criteria andEnvironmentIdLessThanOrEqualTo(Integer value) {
            addCriterion("environment_id <=", value, "environmentId");
            return (Criteria) this;
        }

        public Criteria andEnvironmentIdIn(List<Integer> values) {
            addCriterion("environment_id in", values, "environmentId");
            return (Criteria) this;
        }

        public Criteria andEnvironmentIdNotIn(List<Integer> values) {
            addCriterion("environment_id not in", values, "environmentId");
            return (Criteria) this;
        }

        public Criteria andEnvironmentIdBetween(Integer value1, Integer value2) {
            addCriterion("environment_id between", value1, value2, "environmentId");
            return (Criteria) this;
        }

        public Criteria andEnvironmentIdNotBetween(Integer value1, Integer value2) {
            addCriterion("environment_id not between", value1, value2, "environmentId");
            return (Criteria) this;
        }

        public Criteria andEnvironmentNameIsNull() {
            addCriterion("environment_name is null");
            return (Criteria) this;
        }

        public Criteria andEnvironmentNameIsNotNull() {
            addCriterion("environment_name is not null");
            return (Criteria) this;
        }

        public Criteria andEnvironmentNameEqualTo(String value) {
            addCriterion("environment_name =", value, "environmentName");
            return (Criteria) this;
        }

        public Criteria andEnvironmentNameNotEqualTo(String value) {
            addCriterion("environment_name <>", value, "environmentName");
            return (Criteria) this;
        }

        public Criteria andEnvironmentNameGreaterThan(String value) {
            addCriterion("environment_name >", value, "environmentName");
            return (Criteria) this;
        }

        public Criteria andEnvironmentNameGreaterThanOrEqualTo(String value) {
            addCriterion("environment_name >=", value, "environmentName");
            return (Criteria) this;
        }

        public Criteria andEnvironmentNameLessThan(String value) {
            addCriterion("environment_name <", value, "environmentName");
            return (Criteria) this;
        }

        public Criteria andEnvironmentNameLessThanOrEqualTo(String value) {
            addCriterion("environment_name <=", value, "environmentName");
            return (Criteria) this;
        }

        public Criteria andEnvironmentNameLike(String value) {
            addCriterion("environment_name like", value, "environmentName");
            return (Criteria) this;
        }

        public Criteria andEnvironmentNameNotLike(String value) {
            addCriterion("environment_name not like", value, "environmentName");
            return (Criteria) this;
        }

        public Criteria andEnvironmentNameIn(List<String> values) {
            addCriterion("environment_name in", values, "environmentName");
            return (Criteria) this;
        }

        public Criteria andEnvironmentNameNotIn(List<String> values) {
            addCriterion("environment_name not in", values, "environmentName");
            return (Criteria) this;
        }

        public Criteria andEnvironmentNameBetween(String value1, String value2) {
            addCriterion("environment_name between", value1, value2, "environmentName");
            return (Criteria) this;
        }

        public Criteria andEnvironmentNameNotBetween(String value1, String value2) {
            addCriterion("environment_name not between", value1, value2, "environmentName");
            return (Criteria) this;
        }

        public Criteria andTemperatureIsNull() {
            addCriterion("temperature is null");
            return (Criteria) this;
        }

        public Criteria andTemperatureIsNotNull() {
            addCriterion("temperature is not null");
            return (Criteria) this;
        }

        public Criteria andTemperatureEqualTo(Double value) {
            addCriterion("temperature =", value, "temperature");
            return (Criteria) this;
        }

        public Criteria andTemperatureNotEqualTo(Double value) {
            addCriterion("temperature <>", value, "temperature");
            return (Criteria) this;
        }

        public Criteria andTemperatureGreaterThan(Double value) {
            addCriterion("temperature >", value, "temperature");
            return (Criteria) this;
        }

        public Criteria andTemperatureGreaterThanOrEqualTo(Double value) {
            addCriterion("temperature >=", value, "temperature");
            return (Criteria) this;
        }

        public Criteria andTemperatureLessThan(Double value) {
            addCriterion("temperature <", value, "temperature");
            return (Criteria) this;
        }

        public Criteria andTemperatureLessThanOrEqualTo(Double value) {
            addCriterion("temperature <=", value, "temperature");
            return (Criteria) this;
        }

        public Criteria andTemperatureIn(List<Double> values) {
            addCriterion("temperature in", values, "temperature");
            return (Criteria) this;
        }

        public Criteria andTemperatureNotIn(List<Double> values) {
            addCriterion("temperature not in", values, "temperature");
            return (Criteria) this;
        }

        public Criteria andTemperatureBetween(Double value1, Double value2) {
            addCriterion("temperature between", value1, value2, "temperature");
            return (Criteria) this;
        }

        public Criteria andTemperatureNotBetween(Double value1, Double value2) {
            addCriterion("temperature not between", value1, value2, "temperature");
            return (Criteria) this;
        }

        public Criteria andTDatetimeIsNull() {
            addCriterion("t_datetime is null");
            return (Criteria) this;
        }

        public Criteria andTDatetimeIsNotNull() {
            addCriterion("t_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andTDatetimeEqualTo(Date value) {
            addCriterion("t_datetime =", value, "tDatetime");
            return (Criteria) this;
        }

        public Criteria andTDatetimeNotEqualTo(Date value) {
            addCriterion("t_datetime <>", value, "tDatetime");
            return (Criteria) this;
        }

        public Criteria andTDatetimeGreaterThan(Date value) {
            addCriterion("t_datetime >", value, "tDatetime");
            return (Criteria) this;
        }

        public Criteria andTDatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("t_datetime >=", value, "tDatetime");
            return (Criteria) this;
        }

        public Criteria andTDatetimeLessThan(Date value) {
            addCriterion("t_datetime <", value, "tDatetime");
            return (Criteria) this;
        }

        public Criteria andTDatetimeLessThanOrEqualTo(Date value) {
            addCriterion("t_datetime <=", value, "tDatetime");
            return (Criteria) this;
        }

        public Criteria andTDatetimeIn(List<Date> values) {
            addCriterion("t_datetime in", values, "tDatetime");
            return (Criteria) this;
        }

        public Criteria andTDatetimeNotIn(List<Date> values) {
            addCriterion("t_datetime not in", values, "tDatetime");
            return (Criteria) this;
        }

        public Criteria andTDatetimeBetween(Date value1, Date value2) {
            addCriterion("t_datetime between", value1, value2, "tDatetime");
            return (Criteria) this;
        }

        public Criteria andTDatetimeNotBetween(Date value1, Date value2) {
            addCriterion("t_datetime not between", value1, value2, "tDatetime");
            return (Criteria) this;
        }

        public Criteria andTDatasizeIsNull() {
            addCriterion("t_datasize is null");
            return (Criteria) this;
        }

        public Criteria andTDatasizeIsNotNull() {
            addCriterion("t_datasize is not null");
            return (Criteria) this;
        }

        public Criteria andTDatasizeEqualTo(Integer value) {
            addCriterion("t_datasize =", value, "tDatasize");
            return (Criteria) this;
        }

        public Criteria andTDatasizeNotEqualTo(Integer value) {
            addCriterion("t_datasize <>", value, "tDatasize");
            return (Criteria) this;
        }

        public Criteria andTDatasizeGreaterThan(Integer value) {
            addCriterion("t_datasize >", value, "tDatasize");
            return (Criteria) this;
        }

        public Criteria andTDatasizeGreaterThanOrEqualTo(Integer value) {
            addCriterion("t_datasize >=", value, "tDatasize");
            return (Criteria) this;
        }

        public Criteria andTDatasizeLessThan(Integer value) {
            addCriterion("t_datasize <", value, "tDatasize");
            return (Criteria) this;
        }

        public Criteria andTDatasizeLessThanOrEqualTo(Integer value) {
            addCriterion("t_datasize <=", value, "tDatasize");
            return (Criteria) this;
        }

        public Criteria andTDatasizeIn(List<Integer> values) {
            addCriterion("t_datasize in", values, "tDatasize");
            return (Criteria) this;
        }

        public Criteria andTDatasizeNotIn(List<Integer> values) {
            addCriterion("t_datasize not in", values, "tDatasize");
            return (Criteria) this;
        }

        public Criteria andTDatasizeBetween(Integer value1, Integer value2) {
            addCriterion("t_datasize between", value1, value2, "tDatasize");
            return (Criteria) this;
        }

        public Criteria andTDatasizeNotBetween(Integer value1, Integer value2) {
            addCriterion("t_datasize not between", value1, value2, "tDatasize");
            return (Criteria) this;
        }

        public Criteria andHumidityIsNull() {
            addCriterion("humidity is null");
            return (Criteria) this;
        }

        public Criteria andHumidityIsNotNull() {
            addCriterion("humidity is not null");
            return (Criteria) this;
        }

        public Criteria andHumidityEqualTo(Double value) {
            addCriterion("humidity =", value, "humidity");
            return (Criteria) this;
        }

        public Criteria andHumidityNotEqualTo(Double value) {
            addCriterion("humidity <>", value, "humidity");
            return (Criteria) this;
        }

        public Criteria andHumidityGreaterThan(Double value) {
            addCriterion("humidity >", value, "humidity");
            return (Criteria) this;
        }

        public Criteria andHumidityGreaterThanOrEqualTo(Double value) {
            addCriterion("humidity >=", value, "humidity");
            return (Criteria) this;
        }

        public Criteria andHumidityLessThan(Double value) {
            addCriterion("humidity <", value, "humidity");
            return (Criteria) this;
        }

        public Criteria andHumidityLessThanOrEqualTo(Double value) {
            addCriterion("humidity <=", value, "humidity");
            return (Criteria) this;
        }

        public Criteria andHumidityIn(List<Double> values) {
            addCriterion("humidity in", values, "humidity");
            return (Criteria) this;
        }

        public Criteria andHumidityNotIn(List<Double> values) {
            addCriterion("humidity not in", values, "humidity");
            return (Criteria) this;
        }

        public Criteria andHumidityBetween(Double value1, Double value2) {
            addCriterion("humidity between", value1, value2, "humidity");
            return (Criteria) this;
        }

        public Criteria andHumidityNotBetween(Double value1, Double value2) {
            addCriterion("humidity not between", value1, value2, "humidity");
            return (Criteria) this;
        }

        public Criteria andHDatetimeIsNull() {
            addCriterion("h_datetime is null");
            return (Criteria) this;
        }

        public Criteria andHDatetimeIsNotNull() {
            addCriterion("h_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andHDatetimeEqualTo(Date value) {
            addCriterion("h_datetime =", value, "hDatetime");
            return (Criteria) this;
        }

        public Criteria andHDatetimeNotEqualTo(Date value) {
            addCriterion("h_datetime <>", value, "hDatetime");
            return (Criteria) this;
        }

        public Criteria andHDatetimeGreaterThan(Date value) {
            addCriterion("h_datetime >", value, "hDatetime");
            return (Criteria) this;
        }

        public Criteria andHDatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("h_datetime >=", value, "hDatetime");
            return (Criteria) this;
        }

        public Criteria andHDatetimeLessThan(Date value) {
            addCriterion("h_datetime <", value, "hDatetime");
            return (Criteria) this;
        }

        public Criteria andHDatetimeLessThanOrEqualTo(Date value) {
            addCriterion("h_datetime <=", value, "hDatetime");
            return (Criteria) this;
        }

        public Criteria andHDatetimeIn(List<Date> values) {
            addCriterion("h_datetime in", values, "hDatetime");
            return (Criteria) this;
        }

        public Criteria andHDatetimeNotIn(List<Date> values) {
            addCriterion("h_datetime not in", values, "hDatetime");
            return (Criteria) this;
        }

        public Criteria andHDatetimeBetween(Date value1, Date value2) {
            addCriterion("h_datetime between", value1, value2, "hDatetime");
            return (Criteria) this;
        }

        public Criteria andHDatetimeNotBetween(Date value1, Date value2) {
            addCriterion("h_datetime not between", value1, value2, "hDatetime");
            return (Criteria) this;
        }

        public Criteria andHDatasizeIsNull() {
            addCriterion("h_datasize is null");
            return (Criteria) this;
        }

        public Criteria andHDatasizeIsNotNull() {
            addCriterion("h_datasize is not null");
            return (Criteria) this;
        }

        public Criteria andHDatasizeEqualTo(Integer value) {
            addCriterion("h_datasize =", value, "hDatasize");
            return (Criteria) this;
        }

        public Criteria andHDatasizeNotEqualTo(Integer value) {
            addCriterion("h_datasize <>", value, "hDatasize");
            return (Criteria) this;
        }

        public Criteria andHDatasizeGreaterThan(Integer value) {
            addCriterion("h_datasize >", value, "hDatasize");
            return (Criteria) this;
        }

        public Criteria andHDatasizeGreaterThanOrEqualTo(Integer value) {
            addCriterion("h_datasize >=", value, "hDatasize");
            return (Criteria) this;
        }

        public Criteria andHDatasizeLessThan(Integer value) {
            addCriterion("h_datasize <", value, "hDatasize");
            return (Criteria) this;
        }

        public Criteria andHDatasizeLessThanOrEqualTo(Integer value) {
            addCriterion("h_datasize <=", value, "hDatasize");
            return (Criteria) this;
        }

        public Criteria andHDatasizeIn(List<Integer> values) {
            addCriterion("h_datasize in", values, "hDatasize");
            return (Criteria) this;
        }

        public Criteria andHDatasizeNotIn(List<Integer> values) {
            addCriterion("h_datasize not in", values, "hDatasize");
            return (Criteria) this;
        }

        public Criteria andHDatasizeBetween(Integer value1, Integer value2) {
            addCriterion("h_datasize between", value1, value2, "hDatasize");
            return (Criteria) this;
        }

        public Criteria andHDatasizeNotBetween(Integer value1, Integer value2) {
            addCriterion("h_datasize not between", value1, value2, "hDatasize");
            return (Criteria) this;
        }

        public Criteria andSunIsNull() {
            addCriterion("sun is null");
            return (Criteria) this;
        }

        public Criteria andSunIsNotNull() {
            addCriterion("sun is not null");
            return (Criteria) this;
        }

        public Criteria andSunEqualTo(Double value) {
            addCriterion("sun =", value, "sun");
            return (Criteria) this;
        }

        public Criteria andSunNotEqualTo(Double value) {
            addCriterion("sun <>", value, "sun");
            return (Criteria) this;
        }

        public Criteria andSunGreaterThan(Double value) {
            addCriterion("sun >", value, "sun");
            return (Criteria) this;
        }

        public Criteria andSunGreaterThanOrEqualTo(Double value) {
            addCriterion("sun >=", value, "sun");
            return (Criteria) this;
        }

        public Criteria andSunLessThan(Double value) {
            addCriterion("sun <", value, "sun");
            return (Criteria) this;
        }

        public Criteria andSunLessThanOrEqualTo(Double value) {
            addCriterion("sun <=", value, "sun");
            return (Criteria) this;
        }

        public Criteria andSunIn(List<Double> values) {
            addCriterion("sun in", values, "sun");
            return (Criteria) this;
        }

        public Criteria andSunNotIn(List<Double> values) {
            addCriterion("sun not in", values, "sun");
            return (Criteria) this;
        }

        public Criteria andSunBetween(Double value1, Double value2) {
            addCriterion("sun between", value1, value2, "sun");
            return (Criteria) this;
        }

        public Criteria andSunNotBetween(Double value1, Double value2) {
            addCriterion("sun not between", value1, value2, "sun");
            return (Criteria) this;
        }

        public Criteria andSDatetimeIsNull() {
            addCriterion("s_datetime is null");
            return (Criteria) this;
        }

        public Criteria andSDatetimeIsNotNull() {
            addCriterion("s_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andSDatetimeEqualTo(Date value) {
            addCriterion("s_datetime =", value, "sDatetime");
            return (Criteria) this;
        }

        public Criteria andSDatetimeNotEqualTo(Date value) {
            addCriterion("s_datetime <>", value, "sDatetime");
            return (Criteria) this;
        }

        public Criteria andSDatetimeGreaterThan(Date value) {
            addCriterion("s_datetime >", value, "sDatetime");
            return (Criteria) this;
        }

        public Criteria andSDatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("s_datetime >=", value, "sDatetime");
            return (Criteria) this;
        }

        public Criteria andSDatetimeLessThan(Date value) {
            addCriterion("s_datetime <", value, "sDatetime");
            return (Criteria) this;
        }

        public Criteria andSDatetimeLessThanOrEqualTo(Date value) {
            addCriterion("s_datetime <=", value, "sDatetime");
            return (Criteria) this;
        }

        public Criteria andSDatetimeIn(List<Date> values) {
            addCriterion("s_datetime in", values, "sDatetime");
            return (Criteria) this;
        }

        public Criteria andSDatetimeNotIn(List<Date> values) {
            addCriterion("s_datetime not in", values, "sDatetime");
            return (Criteria) this;
        }

        public Criteria andSDatetimeBetween(Date value1, Date value2) {
            addCriterion("s_datetime between", value1, value2, "sDatetime");
            return (Criteria) this;
        }

        public Criteria andSDatetimeNotBetween(Date value1, Date value2) {
            addCriterion("s_datetime not between", value1, value2, "sDatetime");
            return (Criteria) this;
        }

        public Criteria andSDatasizeIsNull() {
            addCriterion("s_datasize is null");
            return (Criteria) this;
        }

        public Criteria andSDatasizeIsNotNull() {
            addCriterion("s_datasize is not null");
            return (Criteria) this;
        }

        public Criteria andSDatasizeEqualTo(Integer value) {
            addCriterion("s_datasize =", value, "sDatasize");
            return (Criteria) this;
        }

        public Criteria andSDatasizeNotEqualTo(Integer value) {
            addCriterion("s_datasize <>", value, "sDatasize");
            return (Criteria) this;
        }

        public Criteria andSDatasizeGreaterThan(Integer value) {
            addCriterion("s_datasize >", value, "sDatasize");
            return (Criteria) this;
        }

        public Criteria andSDatasizeGreaterThanOrEqualTo(Integer value) {
            addCriterion("s_datasize >=", value, "sDatasize");
            return (Criteria) this;
        }

        public Criteria andSDatasizeLessThan(Integer value) {
            addCriterion("s_datasize <", value, "sDatasize");
            return (Criteria) this;
        }

        public Criteria andSDatasizeLessThanOrEqualTo(Integer value) {
            addCriterion("s_datasize <=", value, "sDatasize");
            return (Criteria) this;
        }

        public Criteria andSDatasizeIn(List<Integer> values) {
            addCriterion("s_datasize in", values, "sDatasize");
            return (Criteria) this;
        }

        public Criteria andSDatasizeNotIn(List<Integer> values) {
            addCriterion("s_datasize not in", values, "sDatasize");
            return (Criteria) this;
        }

        public Criteria andSDatasizeBetween(Integer value1, Integer value2) {
            addCriterion("s_datasize between", value1, value2, "sDatasize");
            return (Criteria) this;
        }

        public Criteria andSDatasizeNotBetween(Integer value1, Integer value2) {
            addCriterion("s_datasize not between", value1, value2, "sDatasize");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table environment
     *
     * @mbggenerated do_not_delete_during_merge Thu Jan 18 14:58:56 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table environment
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}