package com.redobj.repository.core.bean;

import java.util.Date;

public class Goods {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_id
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    private Integer goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_name
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    private String goodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_stock
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    private Integer goodsStock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_env
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    private Integer goodsEnv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_date
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    private Date goodsDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_note
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    private String goodsNote;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_id
     *
     * @return the value of goods.goods_id
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_id
     *
     * @param goodsId the value for goods.goods_id
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_name
     *
     * @return the value of goods.goods_name
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_name
     *
     * @param goodsName the value for goods.goods_name
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_stock
     *
     * @return the value of goods.goods_stock
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    public Integer getGoodsStock() {
        return goodsStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_stock
     *
     * @param goodsStock the value for goods.goods_stock
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    public void setGoodsStock(Integer goodsStock) {
        this.goodsStock = goodsStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_env
     *
     * @return the value of goods.goods_env
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    public Integer getGoodsEnv() {
        return goodsEnv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_env
     *
     * @param goodsEnv the value for goods.goods_env
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    public void setGoodsEnv(Integer goodsEnv) {
        this.goodsEnv = goodsEnv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_date
     *
     * @return the value of goods.goods_date
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    public Date getGoodsDate() {
        return goodsDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_date
     *
     * @param goodsDate the value for goods.goods_date
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    public void setGoodsDate(Date goodsDate) {
        this.goodsDate = goodsDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_note
     *
     * @return the value of goods.goods_note
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    public String getGoodsNote() {
        return goodsNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_note
     *
     * @param goodsNote the value for goods.goods_note
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    public void setGoodsNote(String goodsNote) {
        this.goodsNote = goodsNote == null ? null : goodsNote.trim();
    }
}