package com.redobj.repository.core.bean;

public class WaitSpider {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wait_spider.wait_id
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    private Integer waitId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wait_spider.wait_goods
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    private String waitGoods;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wait_spider.wait_status
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    private Boolean waitStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wait_spider.wait_id
     *
     * @return the value of wait_spider.wait_id
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    public Integer getWaitId() {
        return waitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wait_spider.wait_id
     *
     * @param waitId the value for wait_spider.wait_id
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    public void setWaitId(Integer waitId) {
        this.waitId = waitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wait_spider.wait_goods
     *
     * @return the value of wait_spider.wait_goods
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    public String getWaitGoods() {
        return waitGoods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wait_spider.wait_goods
     *
     * @param waitGoods the value for wait_spider.wait_goods
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    public void setWaitGoods(String waitGoods) {
        this.waitGoods = waitGoods == null ? null : waitGoods.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wait_spider.wait_status
     *
     * @return the value of wait_spider.wait_status
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    public Boolean getWaitStatus() {
        return waitStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wait_spider.wait_status
     *
     * @param waitStatus the value for wait_spider.wait_status
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    public void setWaitStatus(Boolean waitStatus) {
        this.waitStatus = waitStatus;
    }
}