package com.redobj.repository.web.dao;

import com.redobj.repository.web.bean.Container;
import com.redobj.repository.web.bean.ContainerExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ContainerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table container
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    int countByExample(ContainerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table container
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    int deleteByExample(ContainerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table container
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    int deleteByPrimaryKey(Integer containerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table container
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    int insert(Container record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table container
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    int insertSelective(Container record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table container
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    List<Container> selectByExample(ContainerExample example);

    List<Container> selectByExampleWithEnv(ContainerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table container
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    Container selectByPrimaryKey(Integer containerId);

    Container selectByPrimaryKeyWithEnv(Integer containerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table container
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    int updateByExampleSelective(@Param("record") Container record, @Param("example") ContainerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table container
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    int updateByExample(@Param("record") Container record, @Param("example") ContainerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table container
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    int updateByPrimaryKeySelective(Container record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table container
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    int updateByPrimaryKey(Container record);
}