package com.redobj.repository.web.dao;

import com.redobj.repository.web.bean.WaitSpider;
import com.redobj.repository.web.bean.WaitSpiderExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface WaitSpiderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wait_spider
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    int countByExample(WaitSpiderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wait_spider
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    int deleteByExample(WaitSpiderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wait_spider
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    int deleteByPrimaryKey(Integer waitId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wait_spider
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    int insert(WaitSpider record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wait_spider
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    int insertSelective(WaitSpider record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wait_spider
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    List<WaitSpider> selectByExample(WaitSpiderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wait_spider
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    WaitSpider selectByPrimaryKey(Integer waitId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wait_spider
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    int updateByExampleSelective(@Param("record") WaitSpider record, @Param("example") WaitSpiderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wait_spider
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    int updateByExample(@Param("record") WaitSpider record, @Param("example") WaitSpiderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wait_spider
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    int updateByPrimaryKeySelective(WaitSpider record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wait_spider
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    int updateByPrimaryKey(WaitSpider record);
}