package com.redobj.repository.core.dao;

import com.redobj.repository.core.bean.Environment;
import com.redobj.repository.core.bean.EnvironmentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EnvironmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table environment
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    int countByExample(EnvironmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table environment
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    int deleteByExample(EnvironmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table environment
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    int deleteByPrimaryKey(Integer environmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table environment
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    int insert(Environment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table environment
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    int insertSelective(Environment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table environment
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    List<Environment> selectByExample(EnvironmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table environment
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    Environment selectByPrimaryKey(Integer environmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table environment
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    int updateByExampleSelective(@Param("record") Environment record, @Param("example") EnvironmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table environment
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    int updateByExample(@Param("record") Environment record, @Param("example") EnvironmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table environment
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    int updateByPrimaryKeySelective(Environment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table environment
     *
     * @mbggenerated Thu Jan 18 14:58:56 CST 2018
     */
    int updateByPrimaryKey(Environment record);
}