package com.redobj.control.analysis.core.bean;

import java.util.Date;

public class Environment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column environment.environment_id
     *
     * @mbg.generated Sun Jan 14 01:30:18 CST 2018
     */
    private Integer environmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column environment.temperature
     *
     * @mbg.generated Sun Jan 14 01:30:18 CST 2018
     */
    private Double temperature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column environment.t_datetime
     *
     * @mbg.generated Sun Jan 14 01:30:18 CST 2018
     */
    private Date tDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column environment.t_datasize
     *
     * @mbg.generated Sun Jan 14 01:30:18 CST 2018
     */
    private Integer tDatasize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column environment.humidity
     *
     * @mbg.generated Sun Jan 14 01:30:18 CST 2018
     */
    private Double humidity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column environment.h_datetime
     *
     * @mbg.generated Sun Jan 14 01:30:18 CST 2018
     */
    private Date hDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column environment.h_datasize
     *
     * @mbg.generated Sun Jan 14 01:30:18 CST 2018
     */
    private Integer hDatasize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column environment.sun
     *
     * @mbg.generated Sun Jan 14 01:30:18 CST 2018
     */
    private Double sun;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column environment.s_datetime
     *
     * @mbg.generated Sun Jan 14 01:30:18 CST 2018
     */
    private Date sDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column environment.s_datasize
     *
     * @mbg.generated Sun Jan 14 01:30:18 CST 2018
     */
    private Integer sDatasize;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column environment.environment_id
     *
     * @return the value of environment.environment_id
     *
     * @mbg.generated Sun Jan 14 01:30:18 CST 2018
     */
    public Integer getEnvironmentId() {
        return environmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column environment.environment_id
     *
     * @param environmentId the value for environment.environment_id
     *
     * @mbg.generated Sun Jan 14 01:30:18 CST 2018
     */
    public void setEnvironmentId(Integer environmentId) {
        this.environmentId = environmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column environment.temperature
     *
     * @return the value of environment.temperature
     *
     * @mbg.generated Sun Jan 14 01:30:18 CST 2018
     */
    public Double getTemperature() {
        return temperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column environment.temperature
     *
     * @param temperature the value for environment.temperature
     *
     * @mbg.generated Sun Jan 14 01:30:18 CST 2018
     */
    public void setTemperature(Double temperature) {
        this.temperature = temperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column environment.t_datetime
     *
     * @return the value of environment.t_datetime
     *
     * @mbg.generated Sun Jan 14 01:30:18 CST 2018
     */
    public Date gettDatetime() {
        return tDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column environment.t_datetime
     *
     * @param tDatetime the value for environment.t_datetime
     *
     * @mbg.generated Sun Jan 14 01:30:18 CST 2018
     */
    public void settDatetime(Date tDatetime) {
        this.tDatetime = tDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column environment.t_datasize
     *
     * @return the value of environment.t_datasize
     *
     * @mbg.generated Sun Jan 14 01:30:18 CST 2018
     */
    public Integer gettDatasize() {
        return tDatasize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column environment.t_datasize
     *
     * @param tDatasize the value for environment.t_datasize
     *
     * @mbg.generated Sun Jan 14 01:30:18 CST 2018
     */
    public void settDatasize(Integer tDatasize) {
        this.tDatasize = tDatasize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column environment.humidity
     *
     * @return the value of environment.humidity
     *
     * @mbg.generated Sun Jan 14 01:30:18 CST 2018
     */
    public Double getHumidity() {
        return humidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column environment.humidity
     *
     * @param humidity the value for environment.humidity
     *
     * @mbg.generated Sun Jan 14 01:30:18 CST 2018
     */
    public void setHumidity(Double humidity) {
        this.humidity = humidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column environment.h_datetime
     *
     * @return the value of environment.h_datetime
     *
     * @mbg.generated Sun Jan 14 01:30:18 CST 2018
     */
    public Date gethDatetime() {
        return hDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column environment.h_datetime
     *
     * @param hDatetime the value for environment.h_datetime
     *
     * @mbg.generated Sun Jan 14 01:30:18 CST 2018
     */
    public void sethDatetime(Date hDatetime) {
        this.hDatetime = hDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column environment.h_datasize
     *
     * @return the value of environment.h_datasize
     *
     * @mbg.generated Sun Jan 14 01:30:18 CST 2018
     */
    public Integer gethDatasize() {
        return hDatasize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column environment.h_datasize
     *
     * @param hDatasize the value for environment.h_datasize
     *
     * @mbg.generated Sun Jan 14 01:30:18 CST 2018
     */
    public void sethDatasize(Integer hDatasize) {
        this.hDatasize = hDatasize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column environment.sun
     *
     * @return the value of environment.sun
     *
     * @mbg.generated Sun Jan 14 01:30:18 CST 2018
     */
    public Double getSun() {
        return sun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column environment.sun
     *
     * @param sun the value for environment.sun
     *
     * @mbg.generated Sun Jan 14 01:30:18 CST 2018
     */
    public void setSun(Double sun) {
        this.sun = sun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column environment.s_datetime
     *
     * @return the value of environment.s_datetime
     *
     * @mbg.generated Sun Jan 14 01:30:18 CST 2018
     */
    public Date getsDatetime() {
        return sDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column environment.s_datetime
     *
     * @param sDatetime the value for environment.s_datetime
     *
     * @mbg.generated Sun Jan 14 01:30:18 CST 2018
     */
    public void setsDatetime(Date sDatetime) {
        this.sDatetime = sDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column environment.s_datasize
     *
     * @return the value of environment.s_datasize
     *
     * @mbg.generated Sun Jan 14 01:30:18 CST 2018
     */
    public Integer getsDatasize() {
        return sDatasize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column environment.s_datasize
     *
     * @param sDatasize the value for environment.s_datasize
     *
     * @mbg.generated Sun Jan 14 01:30:18 CST 2018
     */
    public void setsDatasize(Integer sDatasize) {
        this.sDatasize = sDatasize;
    }
}