package com.redobj.control.analysis.bean;

public class Environment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column environment.environment_id
     *
     * @mbg.generated Sat Jan 13 14:37:33 CST 2018
     */
    private Integer environmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column environment.temperature
     *
     * @mbg.generated Sat Jan 13 14:37:33 CST 2018
     */
    private Double temperature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column environment.humidity
     *
     * @mbg.generated Sat Jan 13 14:37:33 CST 2018
     */
    private Double humidity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column environment.Illumination
     *
     * @mbg.generated Sat Jan 13 14:37:33 CST 2018
     */
    private Double illumination;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column environment.environment_id
     *
     * @return the value of environment.environment_id
     *
     * @mbg.generated Sat Jan 13 14:37:33 CST 2018
     */
    public Integer getEnvironmentId() {
        return environmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column environment.environment_id
     *
     * @param environmentId the value for environment.environment_id
     *
     * @mbg.generated Sat Jan 13 14:37:33 CST 2018
     */
    public void setEnvironmentId(Integer environmentId) {
        this.environmentId = environmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column environment.temperature
     *
     * @return the value of environment.temperature
     *
     * @mbg.generated Sat Jan 13 14:37:33 CST 2018
     */
    public Double getTemperature() {
        return temperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column environment.temperature
     *
     * @param temperature the value for environment.temperature
     *
     * @mbg.generated Sat Jan 13 14:37:33 CST 2018
     */
    public void setTemperature(Double temperature) {
        this.temperature = temperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column environment.humidity
     *
     * @return the value of environment.humidity
     *
     * @mbg.generated Sat Jan 13 14:37:33 CST 2018
     */
    public Double getHumidity() {
        return humidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column environment.humidity
     *
     * @param humidity the value for environment.humidity
     *
     * @mbg.generated Sat Jan 13 14:37:33 CST 2018
     */
    public void setHumidity(Double humidity) {
        this.humidity = humidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column environment.Illumination
     *
     * @return the value of environment.Illumination
     *
     * @mbg.generated Sat Jan 13 14:37:33 CST 2018
     */
    public Double getIllumination() {
        return illumination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column environment.Illumination
     *
     * @param illumination the value for environment.Illumination
     *
     * @mbg.generated Sat Jan 13 14:37:33 CST 2018
     */
    public void setIllumination(Double illumination) {
        this.illumination = illumination;
    }
}